### ISSUE TITLE
[feature request] Disable logging to LogCat

### ISSUE THREAD

**Issue by danielmmmm** [xenon92/xposed-disable-fullscreen-keyboard#1]
Thanks for your module, it is working well. There is one downside though, that actually made me disable the module. It is spamming LogCat like crazy. After a few minutes, my log is filled with thousands of lines from your module, and it is impossible to debug anything else on my phone.

**Comment by xenon92** [comment]
Fixed in https://github.com/xenon92/xposed-disable-fullscreen-keyboard/commit/a2d78d11cf9f369066e31a25ccb0757d24af7ed2

**Comment by danielmmmm** [comment]
Thanks a lot!
